import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./Home.tsx/Navbar";
import Footer from "./Home.tsx/Footer";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Cyber-Chetana",
  description: "Generated by CyberProbeX",
 icons: {
      icon: "/FINAL.png",
    },
  keywords: [

    
  ],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
     className={`${geistSans.variable} ${geistMono.variable} antialiased selection:bg-black selection:text-white`}
  
      >
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
